In [1]:
import numpy as np

Creating an Array using numpy
i) using the np.array()
ii) using the npasarray()

In [2]:
l = [1,2,3,4,5]
arr = np.array(l)

In [3]:
type(arr)  # ndarray - n dimensional array

numpy.ndarray

In [4]:
a = np.asarray(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.ndim

1

In [10]:
arr1.ndim

2

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
a = arr # shallow copy is being done here

In [13]:
arr[0] = 100

In [14]:
arr

array([100,   2,   3,   4,   5])

In [15]:
a

array([100,   2,   3,   4,   5])

In [16]:
b = np.copy(arr)

In [17]:
arr[1]= 50

In [18]:
arr

array([100,  50,   3,   4,   5])

In [19]:
b

array([100,   2,   3,   4,   5])

In [20]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
x = np.fromfunction(lambda i,j : i*j , (3,3))
x

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [22]:
itera = (i*i for i in range(5))

In [23]:
itera

<generator object <genexpr> at 0x7fd2e426c040>

In [24]:
np.fromiter(itera,int)

array([ 0,  1,  4,  9, 16])

In [25]:
np.fromstring('23 12 24',sep = ' ')

array([23., 12., 24.])

In [26]:
np.fromstring('23,12,24',sep = ',')

array([23., 12., 24.])

In [27]:
x.ndim # returns the dimension of the array

2

In [28]:
x.size # returns total number of elements available in the array

9

In [29]:
x.shape

(3, 3)

In [30]:
b.shape

(5,)

In [31]:
b.dtype

dtype('int64')

In [32]:
x.dtype

dtype('float64')

In [33]:
list(range(5))

[0, 1, 2, 3, 4]

In [34]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [35]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [36]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [37]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [38]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [39]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [40]:
np.logspace(1,5,20,base=10)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [45]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [46]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [47]:
arr = np.ones((3,4))

In [48]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [49]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [50]:
arr1 = np.eye(5)

In [51]:
 np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [52]:
type(arr1)

numpy.ndarray

In [53]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [54]:
np.random.rand(2,3) #noraml distribution dataset

array([[0.70704539, 0.01912053, 0.02809768],
       [0.55798851, 0.55436538, 0.20731848]])

In [55]:
np.random.randn(2,3) #standard normal distribution - mean=0,sd = 1

array([[-0.25383069,  0.36964806, -0.93386305],
       [ 0.89061902,  1.06575472, -0.14587578]])

In [56]:
arr2 = np.random.randint(1,7,(3,4))

In [57]:
arr2

array([[2, 5, 6, 3],
       [5, 3, 2, 1],
       [3, 3, 4, 2]])

In [58]:
arr2.size

12

In [59]:
arr2.shape

(3, 4)

In [60]:
arr2.reshape(4,3)

array([[2, 5, 6],
       [3, 5, 3],
       [2, 1, 3],
       [3, 4, 2]])

In [61]:
arr2.reshape(6,2)

array([[2, 5],
       [6, 3],
       [5, 3],
       [2, 1],
       [3, 3],
       [4, 2]])

In [62]:
arr2.reshape(2,6) #make sure that the r*c = size of array else u will face an error
# for an example i will try to give the reshape value as r*c>size in next code

array([[2, 5, 6, 3, 5, 3],
       [2, 1, 3, 3, 4, 2]])

In [63]:
arr2.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [67]:
arr2.reshape(4,-1)

array([[2, 5, 6],
       [3, 5, 3],
       [2, 1, 3],
       [3, 4, 2]])

In [68]:
arr2.reshape(4,-124356)

array([[2, 5, 6],
       [3, 5, 3],
       [2, 1, 3],
       [3, 4, 2]])

In [69]:
arr2.reshape(2,2,3)

array([[[2, 5, 6],
        [3, 5, 3]],

       [[2, 1, 3],
        [3, 4, 2]]])

In [72]:
arr2.reshape(3,2,2)

array([[[2, 5],
        [6, 3]],

       [[5, 3],
        [2, 1]],

       [[3, 3],
        [4, 2]]])

In [86]:
y = np.random.randint(1,10,(5,6))
y

array([[9, 9, 4, 4, 6, 8],
       [1, 5, 3, 9, 6, 4],
       [3, 4, 8, 2, 1, 9],
       [2, 6, 7, 3, 8, 2],
       [5, 9, 7, 4, 5, 1]])

In [87]:
y>8

array([[ True,  True, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False]])

In [89]:
y[y >8]

array([9, 9, 9, 9, 9])

In [ ]:
y[0]

array([9, 9, 4, 4, 6, 8])

Extracting first 2 elements in the matrix

In [91]:
y[0][0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [92]:
y[0,[0,1]]

array([9, 9])

Extracting 8,2,7,3 matrix from the matrix y

In [100]:
y[[2,3],[2,3]]

array([8, 3])

In [101]:
y[2:4,[2,3]]

array([[8, 2],
       [7, 3]])

Matrix operations- In numpy when we directly try to (add,subtract,multiply,divide) 2 matrices it is done through indexing

In [104]:
x = np.random.randint(1,3,(3,3))
y = np.random.randint(1,3,(3,3))

In [105]:
x

array([[1, 2, 1],
       [2, 2, 1],
       [2, 2, 2]])

In [106]:
y

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [107]:
x+y

array([[2, 4, 2],
       [3, 4, 2],
       [4, 3, 3]])

In [108]:
x-y

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 1]])

In [111]:
x*y #This is not matrix multiplication

array([[1, 4, 1],
       [2, 4, 1],
       [4, 2, 2]])

In [110]:
x/y

array([[1., 1., 1.],
       [2., 1., 1.],
       [1., 2., 2.]])

In [113]:
x@y #This is matrix multiplication

array([[ 5,  7,  4],
       [ 6,  9,  5],
       [ 8, 10,  6]])

In [114]:
x/0

/tmp/ipykernel_1191/373018688.py:1: RuntimeWarning: divide by zero encountered in divide
  x/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Numpy Broadcasting

In [116]:
arr = np.zeros((3,4))

In [117]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
arr = arr+5

In [122]:
a = np.array([1,2,3,4])

In [123]:
arr + a 

array([[6., 7., 8., 9.],
       [6., 7., 8., 9.],
       [6., 7., 8., 9.]])

In [28]:
import numpy as np

x = np.random.randint(1,10,(4,4))

In [29]:
x

array([[2, 5, 3, 4],
       [7, 9, 5, 9],
       [6, 8, 7, 5],
       [2, 9, 8, 4]])

In [30]:
x.reshape(8,2)

array([[2, 5],
       [3, 4],
       [7, 9],
       [5, 9],
       [6, 8],
       [7, 5],
       [2, 9],
       [8, 4]])

In [31]:
x = x.reshape(8,2)

In [32]:
x.T

array([[2, 3, 7, 5, 6, 7, 2, 8],
       [5, 4, 9, 9, 8, 5, 9, 4]])

In [33]:
x.flatten()

array([2, 5, 3, 4, 7, 9, 5, 9, 6, 8, 7, 5, 2, 9, 8, 4])

In [34]:
x = x.reshape(8,2)

In [35]:
np.expand_dims(x,axis=1)

array([[[2, 5]],

       [[3, 4]],

       [[7, 9]],

       [[5, 9]],

       [[6, 8]],

       [[7, 5]],

       [[2, 9]],

       [[8, 4]]])

Shape: (8, 1, 2)
Structure: This array consists of 8 elements, where each element is a row containing a single 2-element array.

In [36]:
np.expand_dims(x,axis=0)

array([[[2, 5],
        [3, 4],
        [7, 9],
        [5, 9],
        [6, 8],
        [7, 5],
        [2, 9],
        [8, 4]]])

Shape: (1, 8, 2)
Structure: This array consists of a single element (a single row), and that element contains 8 rows, where each row is a 2-element array.

In [37]:
data = np.array([[1],[2],[3]]) #2-dimensional data

In [38]:
np.squeeze(data) #squeezed into 1-dimension

array([1, 2, 3])

In [39]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [45]:
np.roll(data,1) # rotates the data from back and push to front

array([[3],
       [1],
       [2]])

In [46]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [51]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [52]:
#numpy-binary operators 

In [4]:
a = np.random.randint(1,4,(3,4))
b = np.random.randint(1,4,(3,4))

In [55]:
a

array([[3, 2, 3, 1],
       [3, 2, 2, 1],
       [1, 2, 2, 3]])

In [56]:
b

array([[2, 3, 2, 1],
       [3, 3, 1, 1],
       [1, 2, 1, 2]])

In [54]:
a**b

array([[ 9,  8,  9,  1],
       [27,  8,  2,  1],
       [ 1,  4,  2,  9]])

In [57]:
~a

array([[-4, -3, -4, -2],
       [-4, -3, -3, -2],
       [-2, -3, -3, -4]])

In [58]:
~a>b

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [75]:
a = np.array(["SUdh VInay","kUmar"])

In [76]:
np.char.upper(a)

array(['SUDH VINAY', 'KUMAR'], dtype='<U10')

In [77]:
np.char.lower(a)

array(['sudh vinay', 'kumar'], dtype='<U10')

In [78]:
np.char.capitalize(a)

array(['Sudh vinay', 'Kumar'], dtype='<U10')

In [79]:
np.char.title(a)

array(['Sudh Vinay', 'Kumar'], dtype='<U10')

In [80]:
#Numpy Mathematical Functions

In [83]:
a = np.random.randint(1,4,(3,4))
a

array([[3, 3, 3, 2],
       [1, 2, 3, 3],
       [2, 2, 2, 2]])

In [84]:
np.sin(a)

array([[0.14112001, 0.14112001, 0.14112001, 0.90929743],
       [0.84147098, 0.90929743, 0.14112001, 0.14112001],
       [0.90929743, 0.90929743, 0.90929743, 0.90929743]])

In [85]:
np.cos(a)

array([[-0.9899925 , -0.9899925 , -0.9899925 , -0.41614684],
       [ 0.54030231, -0.41614684, -0.9899925 , -0.9899925 ],
       [-0.41614684, -0.41614684, -0.41614684, -0.41614684]])

In [86]:
np.tan(a)

array([[-0.14254654, -0.14254654, -0.14254654, -2.18503986],
       [ 1.55740772, -2.18503986, -0.14254654, -0.14254654],
       [-2.18503986, -2.18503986, -2.18503986, -2.18503986]])

In [87]:
np.log10(a)

array([[0.47712125, 0.47712125, 0.47712125, 0.30103   ],
       [0.        , 0.30103   , 0.47712125, 0.47712125],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ]])

In [88]:
np.exp(a)

array([[20.08553692, 20.08553692, 20.08553692,  7.3890561 ],
       [ 2.71828183,  7.3890561 , 20.08553692, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [89]:
np.power(a,2)

array([[9, 9, 9, 4],
       [1, 4, 9, 9],
       [4, 4, 4, 4]])

In [90]:
np.mean(a)

2.3333333333333335

In [91]:
np.median(a)

2.0

In [96]:
# Sample NumPy array
arr = np.array([1, 2, 3, 4, 3, 2, 2, 4, 4, 5, 5])

# Get unique elements and their respective counts
unique_elements, element_counts = np.unique(arr, return_counts=True)

# Find the index of the element with the highest count (mode)
mode_index = np.argmax(element_counts)

# The mode is the element with the highest count
mode = unique_elements[mode_index]

print("Array:", arr)
print("Mode:", mode)


Array: [1 2 3 4 3 2 2 4 4 5 5]
Mode: 2


In [92]:
np.std(a)

0.6236095644623236

In [93]:
np.var(a)

0.388888888888889

In [94]:
np.min(a)

1

In [95]:
np.max(a)

3

In [97]:
#Arthemetic Operations

In [5]:
a 

array([[1, 1, 1, 2],
       [2, 3, 1, 2],
       [1, 2, 1, 2]])

In [6]:
b

array([[1, 1, 1, 3],
       [3, 1, 2, 3],
       [3, 1, 2, 1]])

In [7]:
a+b

array([[2, 2, 2, 5],
       [5, 4, 3, 5],
       [4, 3, 3, 3]])

In [11]:
np.add(a,b)

array([[2, 2, 2, 5],
       [5, 4, 3, 5],
       [4, 3, 3, 3]])

In [10]:
np.subtract(a,b)

array([[ 0,  0,  0, -1],
       [-1,  2, -1, -1],
       [-2,  1, -1,  1]])

In [12]:
np.multiply(a,b)

array([[1, 1, 1, 6],
       [6, 3, 2, 6],
       [3, 2, 2, 2]])

In [13]:
np.mod(a,b)

array([[0, 0, 0, 2],
       [2, 0, 1, 2],
       [1, 0, 1, 0]])

In [20]:
np.power(a,b)

array([[1, 1, 1, 8],
       [8, 3, 1, 8],
       [1, 2, 1, 2]])

In [16]:
np.sqrt(a)

array([[1.        , 1.        , 1.        , 1.41421356],
       [1.41421356, 1.73205081, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        , 1.41421356]])

In [25]:
arr = np.array([7,2,3,5,6])

In [26]:
np.sort(arr)

array([2, 3, 5, 6, 7])

In [29]:
np.searchsorted(arr,8) #Basically this function gives you the index that where should given number in a sorted array

5

In [30]:
np.searchsorted(arr,4)

3

In [31]:
arr1 = np.array([1,2,3,4,5,0,0,0,2,3])

In [32]:
np.count_nonzero(arr1)

7

In [34]:
np.where(arr1 > 0) # gives the indexs where conditions satisfies

(array([0, 1, 2, 3, 4, 8, 9]),)

In [35]:
np.extract(arr1 > 1,arr1)

array([2, 3, 4, 5, 2, 3])

In [ ]:
#Numpy - Bite Swapping

In [36]:
arr1

array([1, 2, 3, 4, 5, 0, 0, 0, 2, 3])

In [37]:
arr1.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680,                  0,
                        0,                  0, 144115188075855872,
       216172782113783808])

In [38]:
arr1

array([1, 2, 3, 4, 5, 0, 0, 0, 2, 3])

In [39]:
arr1.byteswap(True) #If I place True here then it will become permanent change to the variable

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680,                  0,
                        0,                  0, 144115188075855872,
       216172782113783808])

In [40]:
arr1

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680,                  0,
                        0,                  0, 144115188075855872,
       216172782113783808])

In [41]:
a = np.copy(arr) #deepcopy

In [42]:
a

array([7, 2, 3, 5, 6])

In [43]:
b = arr.view()

In [44]:
b

array([7, 2, 3, 5, 6])

In [45]:
b[0] = 10 

In [46]:
b

array([10,  2,  3,  5,  6])

In [47]:
arr

array([10,  2,  3,  5,  6])

In [48]:
a

array([7, 2, 3, 5, 6])

In [49]:
import numpy.matlib as nm

In [50]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [51]:
nm.zeros((3,5))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [52]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [53]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#Numpy-Linear Algebra

In [73]:
a = np.random.randint([[2,3],[4,5]])

In [74]:
a

array([[1, 0],
       [1, 3]])

In [71]:
b = np.random.randint([[5,3],[2,5]])

In [72]:
b

array([[1, 1],
       [1, 1]])

In [75]:
np.dot(a,b)

array([[1, 1],
       [4, 4]])

In [76]:
a@b

array([[1, 1],
       [4, 4]])

In [77]:
a.transpose()

array([[1, 1],
       [0, 3]])